---
title: "HIC"
author: "Ryan"
date: "October 6, 2015"
output: html_document
---

## Plotting setting
```{r}
library(ggplot2)
library(ggthemes)
library(gridExtra)
theme_set(theme_minimal())
```

## Some example data
What is the structure on every possible level?  
```{r}
data <- data.frame(x = c(1,0,2,5,4,5,1,0,2,6,6,4,3,3,4,4,5,5),
                   y = c(2,0,1,3,1,0,-1,1,0,2,1,2,6,7,8,5,6,7))
p <- ggplot(aes(x = x, y = y, label=rownames(data)), data = data) + 
    geom_point(size = 5) + 
    xlim(-2,8) + 
    ylim(-2,8) + 
    geom_text(hjust = 2)
plot(p)
```

## Calculate distances using `dist()` 
```{r}
d <- dist(data, method = "euclidean")
round(as.matrix(d),2)
sqrt(sum((data[1,]-data[2,])^2))
d[1]
```

## Big Idea   
Iterativly collapse the closest two points into a new point    
```{r}
data.hic <- hclust(d)
plot(data.hic, hang = -1)
plot(p)
```

cut the three to get 3 clusters
```{r}
groups.three = cutree(data.hic,3)
groups.three
ggplot(aes(x = x, y = y, label=rownames(data)), data = data) + 
    geom_point(size = 5, color = groups.three) + 
    xlim(-2,8) + 
    ylim(-2,8) + 
    geom_text(hjust = 2)
```

To see all possible segemantation
```{r}
for (i in 1:18){
    groups = cutree(data.hic, 18-i+1)
    print(groups)
    centroids <- aggregate(data,list(groups),mean)
    print(t(centroids))
    p <- ggplot(aes(x = x, y = y, label=rownames(data)), data = data) + 
        geom_point(size = 5, color = groups) + 
        xlim(-2,8) + 
        ylim(-2,8)
    plot(p)
}
```


```{r}
aggregate(data,list(groups.three),mean)
```

